In [28]:
import numpy as np

v = np.zeros(12)
v[5] = 1
print(v)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [29]:
# create a vector with value ranging from 10 to 100
b=np.arange(10,100)
print(b)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [30]:
b=np.arange(10,19).reshape(3,3)
print(b)


[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [31]:
# to generate identity matrix
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# ccrete to random matrix 3,3,3
d=np.random.random((3,3,3))
print(d)

[[[0.58952538 0.72063213 0.51959706]
  [0.77283363 0.45524037 0.23541549]
  [0.6647867  0.31030229 0.17367741]]

 [[0.5010435  0.89210221 0.7609223 ]
  [0.01176901 0.52969874 0.57840534]
  [0.00127086 0.13157368 0.02207278]]

 [[0.4585182  0.93514558 0.84319549]
  [0.90641693 0.27363466 0.00157163]
  [0.81251051 0.69497472 0.57333841]]]


In [33]:
# to create a 5*5 array with random value
d=np.random.random((5,4))
dmin,dmax=d.min(),d.max
print(dmin,dmax)

0.13366587470187308 <built-in method max of numpy.ndarray object at 0x000001C43EFA9410>


In [34]:
v = np.zeros(20)
v[5]=1
print(v)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
